apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 80
      nodePort: 1080
      name: http port
    - protocol: TCP
      port: 1443
      targetPort: 443
      nodePort: 1443
      name: https port
    - protocol: TCP
      port: 1663
      targetPort: 663
      nodePort: 1663
      name: static-port
    - protocol: TCP
      port: 1773
      targetPort: 773
      nodePort: 1773
      name: openim-port
    - protocol: TCP
      port: 1783
      targetPort: 783
      nodePort: 1783
      name: minio-openim-port
